language: r
sudo: false
cache: packages
dist: xenial

services:
  - docker
before_script:
  ./scripts/selenium-start

r_packages:
  - covr
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
