language: r
sudo: false
cache: packages
dist: bionic

services:
  - docker
before_script:
  ./scripts/selenium-start

r_packages:
  - covr
r_github_packages:
  - cran/curl@3.3
after_success:
  - Rscript -e 'covr::codecov(quiet = FALSE)'
